name = "edo"
uuid = "5af93a52-9085-418c-bfc0-c4b5ac23e7d2"
authors = ["Pablo Rodríguez Sánchez <pablo.rodriguez.sanchez@gmail.com>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
